# version: '3.8'

services:
  web:
    build: .
    container_name: fastapi_service
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:Teja%401234@db/User  # Ensure the credentials match your config

  db:
    image: postgres:15
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Teja@1234
      POSTGRES_DB: User
    ports:
      - "5432:5432"

volumes:
  postgres_data:
